version: "3.9"

networks:
  default:
    name: loadbalancer2_default

services:
  app1:
    build:
      context: ./app
    container_name: app1
    hostname: app1
    ports:
      - "8081:80"

  app2:
    build:
      context: ./app
    container_name: app2
    hostname: app2
    ports:
      - "8082:80"

  app3:
    build:
      context: ./app
    container_name: app3
    hostname: app3
    ports:
      - "8083:80"

  loadbalancer:
      image: "docker.io/haproxy:alpine"
      container_name: loadbalancer
      ports:
        - "8080:8080"
      volumes:
        - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg  
      depends_on:
        - app1
        - app2
        - app3
      networks:
        - default
